<?php
	
	include_once "API.php";
		
?>

<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type"	content="text/html; charset=windows-1255">
<title>Game</title>

<link rel="stylesheet" href="styles.css">
<link href='http://fonts.googleapis.com/css?family=Roboto:400,700' rel='stylesheet'>

<script src="jquery-1.11.1.js"></script>
<script src="functions.js"></script>
<script>

//set global variables to be transferrable between functions: 
var	max_num = 0;
var level = "";
var next_num = 0;
var arrayToShuffle = []; //empty array to be generated by game size, and then shuffled.
var score = 0;


	// when user clicks a level:
	
	$(function() {
		
		$("[name='level']").click(function() {

		//reset game elements:
		 
			//show start button if hidden
			$(".btnStartStop, #table_game_blocks").show();
			
			//Stop and reset timer:
			stopTimer();

			//reset start/stop buttons:
			$("#start").css({"background-color": "#FF4562"}).val("start!");

			//reset Next Number to 0: 
			$("#next_num").html(0);
			
		// generate game board:
			
			//determine game board size and open it:
			level = $(this).attr("id"); 			// game size as string (stringable to tags' ID attributes)
			max_num = parseInt($(this).attr("id")); // game size as integer for use in calculations. 
			$("#table_game_blocks").empty();		// "var" omitted to make this variable transferrable between functions.
			generate_game_size(max_num, level);
			
			//adjust Start button width based on chosen board size: 
			var buttonWidth = Math.sqrt(max_num) * 47 - 51;
			$("#start").css({"width": buttonWidth + "px"});
			
		});	

	});


	// if user clicks a gray block before clicking "Start" button:
	$(function() {

		$("#table_game_blocks").on("click", ".gray_block", function() {
			$(this).fadeToggle(80).fadeToggle(80).fadeToggle(80).fadeToggle(80);
		});

	});

	//when user clicks "Start" button:
	
	$(function() {
			
		$("#start").click(function() {

		//set game elements to game start:
			
			//start timer: 
			startTimer();

			//set next_num to 1: 
			next_num = 1;
			$("#next_num").html(next_num);

			//change "start" button color and caption: 
			$("#start").css({"background-color": "gray"}).val("start over");
			
		//randomize game cube numbers in game board
		
			//populate declared empty array with range of 1 to maximum number, based on chosen level:
			for (var i = 1; i <= max_num; i++) {
				arrayToShuffle.push(i);
			}
			
			//shuffle the generated array: 
			var shuffled = shuffle(arrayToShuffle);

			//push suffled array into game cubes, based on game size:
			var div_start = "<div class='num_block' style='background-color:#48A648'><span class='num_span'>";
			var div_end = "</span><div>";
			$("#game_blocks_" + level).empty();

			//add game cubes to board:
			for(var i = 0; i <= max_num - 1; i++) {
				$("#game_blocks_" + level).append(div_start + shuffled[i] + div_end);
			}	
				
		});
		
	});

	//when user clicks a game cube, get clicked num and next num, and check user click sequence on cubes: 

	$(function() {

		$("#table_game_blocks").on("click", ".num_block", function() {

			//get the number inside clicked game cube (children == span)
			var clicked_num = $(this).children().text();

			// if user clicked the correct num in sequence: 
			if(clicked_num == next_num) {
				 
				//advance next num:
				next_num++;
				
				// put next_num into html:
				$("#next_num").html(next_num); 	

				// fade out the clicked num:					
				$(this).fadeTo("fast", 0);	

				//if user clicked max number (i.e. won), end game:
				if(next_num > max_num) {
					
					//get game time:  
					var game_time = parseInt($("#game_time").html()); 
					window.name = calculateScore(max_num, game_time); //save to window.name to pass variable to Scores page.
					
					//stop timer and go to Scores page:
					stopTimer();
					window.location.assign("scores.php");
					
				}
					
			}
			else {
				$(this).fadeToggle(80).fadeToggle(80).fadeToggle(80).fadeToggle(80);
				
			}
			
		});

	});	

	//if user clicks "quit", close game board, and reset timer and next num: 
	
	$(function() {
			
		$("#quit").click(function() {

			// close game board: 
			$(".btnStartStop,#table_game_blocks").slideUp(500, "linear");

			//stop timer:
			stopTimer();

			//reset next num to 0. 
			$("#next_num").html(0);
			
		});
		
	});
	
</script>

</head>

<body>

	<section id="sec_game">


		<!-- Game Levels -->

		<div class="optionsWrap">

			<div id="levelBtns">

				<input type="button" class="btnLevel" id="16" name="level" value="low" /> 
				<input type="button" class="btnLevel" id="25" name="level" value="med" /> 
				<input type="button" class="btnLevel" id="36" name="level" value="high" />
				<span class="stretch"></span>
			</div>

			<div class="label" id="lblLevel">
				<hr class="brace" />
				choose level
			</div>

		</div>


		<!-- Game Info -->

		<div id="containerIndex">
			<div class="game_info_item">
				<span id="game_time">0</span><br />
				<span class="label">elapsed</span>
			</div>
			<div class="game_info_item">
				<span id="next_num">0</span><br />
				<span class="label">next</span>
			</div>
			<span class="stretch"></span>
		</div>


		<!-- Game Board with Start/Quit buttons-->

		<div id="table_game_blocks" style="display: none"></div>
		<input type="button" class="btnStartStop" id="start" value="start!"
			style="display: none" /> <input type="button" class="btnStartStop"
			id="quit" value="quit" style="display: none" />

	</section>


	<footer>

		<span>&copy; All rights reserved.</span>

	</footer>

</body>

</html>